modLoader = "javafml"
loaderVersion = "[36,)"
license = "MIT"

[[mods]]
modId = "sparsestructuresreforged"
version = "${version}"
displayName = "SparseStructuresReforged"
authors = "TeamPotato"
description = '''
A Minecraft Mod.
'''

[[dependencies.sparsestructuresreforged]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"
