modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
modId = "sparsestructuresreforged"
version = "${version}"
displayName = "SparseStructuresReforged"
authors = "TeamPotato"
description = '''
A Minecraft Mod.
'''

[[mixins]]
config = "sparsestructuresreforged.mixins.json"