modLoader="javafml"
loaderVersion="[36,)"
license="MIT"

[[mods]]
modId="sparsestructuresreforged"
version="${file.jarVersion}"
displayName="SparseStructuresReforged"
authors="TeamPotato"
description='''
A Minecraft mod.
'''